language: ruby
rvm:
- 2.1

before_script:
 - chmod +x travis.sh

script: ./travis.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - gh-pages

notifications:
  email: false

install:
 - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
 - cd $TRAVIS_REPO_SLUG
 - git checkout -qf $TRAVIS_COMMIT
